In [1]:
import pandas as pd
data=pd.DataFrame([
        [100,'Tom','MGR','4500'],
        [200,'Mary','Pgmr','6000'],
        [300,'JOn','HR',5400],
        [400,'Larry','pgmr',7800],
        [500,'Peter','Clerk',3500],
        [600,'Kate','HR',400]
     ]) # now we have created dataframe but without column name

# 9 DAY 9_Data cleaning_EDA
WHat is EDA - EDA is nothing but extracting, cleaning and visualizing the data to identify patterns from the data.
In Python, EDA typically involves the following steps:
1) Loading the Data: Using libraries like pandas to load data into DataFrame structures.

2) Data Cleaning: Identifying missing values, outliers, or inconsistencies and handling them by filling, removing, or correcting the data.

3) Descriptive Statistics: Using methods like .describe() in pandas to compute basic summary statistics (mean, median, standard deviation, etc.) of the dataset.

4) Visualizing the Data: Using libraries such as matplotlib, seaborn, or plotly to create plots like histograms, box plots, scatter plots, and correlation heatmaps to visualize the distribution of data and relationships between variables.

5) Identifying Patterns: Looking for trends, patterns, and anomalies in the data that might suggest a deeper investigation or features for modeling.

   Steps IN EDA
- 9.1 Rename
- 9.2 remove duplicates¶
- 9.3 Remove unwanted columns
- 9.4 Handling null values(null value imputation)
- 9.5 combining multiple data frames
- - 3 ways to combine the dataset.
  - 9.5.1 join - data set will appended to next each other
                - NO of rows should be same.
  - 9.5.2 Concat - No of column should be same.
                - if column names are same to each other in both set then data will be appended one aboe the other.
                - if column names are different to each other then columns will appended next to each other.
  - 9.5.3 Merge - Similar to join in DB
- 9.6 Group records
- 9.7 Sorting

## 9.1 Rename

In [5]:
type(data)

pandas.core.frame.DataFrame

In [7]:
data.columns=['Eid','Ename','Job','Salary'] # assigning the column name to crated daraframe
data

   Eid  Ename    Job Salary
0  100    Tom    MGR   4500
1  200   Mary   Pgmr   6000
2  300    JOn     HR   5400
3  400  Larry   pgmr   7800
4  500  Peter  Clerk   3500
5  600   Kate     HR    400

In [9]:
data.index=['e1','e2','e3','e4','e5','e6'] # assigning the row name to created daraframe
data

    Eid  Ename    Job Salary
e1  100    Tom    MGR   4500
e2  200   Mary   Pgmr   6000
e3  300    JOn     HR   5400
e4  400  Larry   pgmr   7800
e5  500  Peter  Clerk   3500
e6  600   Kate     HR    400

In [11]:
data.rename(columns={
                        'Ename':'name',
                        'JOb':'Role',
                        'Salary':'sal'
                    }
           )

    Eid   name    Job   sal
e1  100    Tom    MGR  4500
e2  200   Mary   Pgmr  6000
e3  300    JOn     HR  5400
e4  400  Larry   pgmr  7800
e5  500  Peter  Clerk  3500
e6  600   Kate     HR   400

In [13]:
data

    Eid  Ename    Job Salary
e1  100    Tom    MGR   4500
e2  200   Mary   Pgmr   6000
e3  300    JOn     HR   5400
e4  400  Larry   pgmr   7800
e5  500  Peter  Clerk   3500
e6  600   Kate     HR    400

In [15]:
data.rename(columns={
                        'Ename':'name',
                        'JOb':'Role',
                        'Salary':'sal'
                    },inplace=True
           )

In [17]:
data

    Eid   name    Job   sal
e1  100    Tom    MGR  4500
e2  200   Mary   Pgmr  6000
e3  300    JOn     HR  5400
e4  400  Larry   pgmr  7800
e5  500  Peter  Clerk  3500
e6  600   Kate     HR   400

In [19]:
#data=pd.DataFrame(data,columns=['Eid','Ename','Job','Salary'],index=['e1','e2','e3','e4','e5','e6'])
#data

In [21]:
import pandas as pd
df1=pd.read_csv(r'\Users\Pandhari\python_practice\Salaries.csv')
df1.head(5)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [22]:
df1.rename(columns={'phd':'doctorate'})
df1.head(5)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [25]:
df1.head(5)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [27]:
df1.rename(columns={'phd':'doctorate'},inplace=True)# it will change the name in real dataframe

In [29]:
df1.head(5)

        rank discipline  doctorate  service   sex  salary
0       Prof          B         56       49  Male  186960
1       Prof          A         20       20  Male  122400
2  AssocProf          A         20       17  Male   81285
3       Prof          B         23       23  Male  134778
4   AsstProf          B          1        0  Male   88000

In [31]:
df1.rename({'0':'ee1'},axis=0)# it will change the name in real dataframe
df1.head(5)

        rank discipline  doctorate  service   sex  salary
0       Prof          B         56       49  Male  186960
1       Prof          A         20       20  Male  122400
2  AssocProf          A         20       17  Male   81285
3       Prof          B         23       23  Male  134778
4   AsstProf          B          1        0  Male   88000

In [33]:
df1.head(5)

        rank discipline  doctorate  service   sex  salary
0       Prof          B         56       49  Male  186960
1       Prof          A         20       20  Male  122400
2  AssocProf          A         20       17  Male   81285
3       Prof          B         23       23  Male  134778
4   AsstProf          B          1        0  Male   88000

## 9.2 Remove duplicate rows

In [36]:
ddup = pd.DataFrame({'col1':['A','A','B','B','B'],'col2':[2,2,2,3,3]})
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [38]:
ddup.drop_duplicates()

  col1  col2
0    A     2
2    B     2
3    B     3

## 9.3 Remove unwanted rows and columns
- Drop is used to drop rows as well as column

In [41]:
data

    Eid   name    Job   sal
e1  100    Tom    MGR  4500
e2  200   Mary   Pgmr  6000
e3  300    JOn     HR  5400
e4  400  Larry   pgmr  7800
e5  500  Peter  Clerk  3500
e6  600   Kate     HR   400

In [43]:
data.drop('e1',
         #inplcae=True,
         #axis=0 -- this is otional as bydefault it drop rows only
         )

    Eid   name    Job   sal
e2  200   Mary   Pgmr  6000
e3  300    JOn     HR  5400
e4  400  Larry   pgmr  7800
e5  500  Peter  Clerk  3500
e6  600   Kate     HR   400

In [45]:
data.drop('Eid',
         axis=1 # mandatory when we dropping the column
         )

     name    Job   sal
e1    Tom    MGR  4500
e2   Mary   Pgmr  6000
e3    JOn     HR  5400
e4  Larry   pgmr  7800
e5  Peter  Clerk  3500
e6   Kate     HR   400

In [47]:
#dir(pd.DataFrame)

In [49]:
data['Eid'].unique() # Given unique calues from column

array([100, 200, 300, 400, 500, 600], dtype=int64)

In [51]:
data['Eid'].nunique() # Gives no of unique values from column

6

In [53]:
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [55]:
#ddup.drop('col1')

In [57]:
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [59]:
#ddup.drop('col1')

In [61]:
ddup.drop('col1',axis=1)

   col2
0     2
1     2
2     2
3     3
4     3

In [63]:
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [65]:
ddup.drop('col1',axis=1,inplace=True)

In [67]:
ddup

   col2
0     2
1     2
2     2
3     3
4     3

In [69]:
ddup.drop(0,axis=0,inplace=True)

In [71]:
ddup

   col2
1     2
2     2
3     3
4     3

## 9.4 Handling null values(null value imputation)
- 9.4.1 Mean
- 9.4.2 Median - middle value
- 9.4.2 Mode - most occured valu - always return output with index

In [74]:
import numpy as np
import pandas as pd

In [76]:
dnull = [ [1,2,3,'M',7],
         [np.nan,5,6,np.nan,7],
         [8,np.nan,9,'F',10],
         [np.nan,np.nan,np.nan,'M',11] 
        ]

dframe = pd.DataFrame(dnull, columns=['a','b','c','d','e'])

In [78]:
dframe.head()

     a    b    c    d   e
0  1.0  2.0  3.0    M   7
1  NaN  5.0  6.0  NaN   7
2  8.0  NaN  9.0    F  10
3  NaN  NaN  NaN    M  11

In [80]:
dnull

[[1, 2, 3, 'M', 7],
 [nan, 5, 6, nan, 7],
 [8, nan, 9, 'F', 10],
 [nan, nan, nan, 'M', 11]]

In [82]:
dframe.dropna()# it drops all the wrows which contains atleast one null value

     a    b    c  d  e
0  1.0  2.0  3.0  M  7

In [84]:
dframe

     a    b    c    d   e
0  1.0  2.0  3.0    M   7
1  NaN  5.0  6.0  NaN   7
2  8.0  NaN  9.0    F  10
3  NaN  NaN  NaN    M  11

In [86]:
dframe.dropna(axis=1) # it drops all the columns(only) which contains atleast one null value

    e
0   7
1   7
2  10
3  11

### 9.4.1 null value imputation

In [89]:
dframe.fillna(0)# it will fill 0 every where irespective to the column data type

     a    b    c  d   e
0  1.0  2.0  3.0  M   7
1  0.0  5.0  6.0  0   7
2  8.0  0.0  9.0  F  10
3  0.0  0.0  0.0  M  11

In [91]:
avg_a=dframe['a'].mean()
avg_b=dframe['b'].mean()
avg_c=dframe['c'].mean()

In [93]:
avg_a

4.5

In [95]:
avg_b

3.5

In [97]:
avg_c

6.0

In [99]:
dframe['d']

0      M
1    NaN
2      F
3      M
Name: d, dtype: object

In [101]:
dframe['d'].mode() # it will display output with index. so we may have a problem to capture

0    M
Name: d, dtype: object

In [103]:
a_mode=dframe['d'].mode() # as it is returning output with index it will not help us to capture the values in variable
a_mode

0    M
Name: d, dtype: object

In [105]:
dframe['d'].mode()[0]

'M'

In [107]:
d_mode=dframe['d'].mode()[0]
d_mode

'M'

In [109]:
dframe.fillna({'a':avg_a,'b':avg_b,'c':avg_c,'d':d_mode})

     a    b    c  d   e
0  1.0  2.0  3.0  M   7
1  4.5  5.0  6.0  M   7
2  8.0  3.5  9.0  F  10
3  4.5  3.5  6.0  M  11

In [111]:
dframe

     a    b    c    d   e
0  1.0  2.0  3.0    M   7
1  NaN  5.0  6.0  NaN   7
2  8.0  NaN  9.0    F  10
3  NaN  NaN  NaN    M  11

In [113]:
dframe.fillna({'a':avg_a,'b':avg_b,'c':avg_c,'d':d_mode},inplace=True)

In [115]:
dframe

     a    b    c  d   e
0  1.0  2.0  3.0  M   7
1  4.5  5.0  6.0  M   7
2  8.0  3.5  9.0  F  10
3  4.5  3.5  6.0  M  11

## 9.5 Combining dataframes

### 9.5.1 Join - will add the data frame next to each other

In [119]:
d1=[[1,2,3],[4,5,6]]

In [121]:
type(d1)

list

In [123]:
df1=pd.DataFrame(d1,columns=['a','b','c'])
df1

   a  b  c
0  1  2  3
1  4  5  6

In [125]:
d2=[[10,20,30],[40,50,60]]
df2=pd.DataFrame(d2,columns=['d','e','f'])
df2

    d   e   f
0  10  20  30
1  40  50  60

In [127]:
df1.join(df2) # padded next to each other

   a  b  c   d   e   f
0  1  2  3  10  20  30
1  4  5  6  40  50  60

In [129]:
df1

   a  b  c
0  1  2  3
1  4  5  6

In [131]:
d10=[[10,20],[40,50]]
df10=pd.DataFrame(d10,columns=['d','e'])
df10

    d   e
0  10  20
1  40  50

In [133]:
df1.join(df10)

   a  b  c   d   e
0  1  2  3  10  20
1  4  5  6  40  50

In [135]:
d12=[[10,20],[40,50],[60,70]]
df12=pd.DataFrame(d12,columns=['d','e'])
df12
#df1.join(df10)

    d   e
0  10  20
1  40  50
2  60  70

In [137]:
df1.join(df10)

   a  b  c   d   e
0  1  2  3  10  20
1  4  5  6  40  50

### 9.5.3 Concat

In [140]:
d3=[[11,22,33],[44,55,66]]
df3=pd.DataFrame(d3,columns=['a','b','c'])
df3

    a   b   c
0  11  22  33
1  44  55  66

In [142]:
pd.concat([df1,df3])# concatenating 2 dataset where we have same column name

    a   b   c
0   1   2   3
1   4   5   6
0  11  22  33
1  44  55  66

In [144]:
pd.concat([df1,df2])# concatenating 2 dataset where we have different column name

     a    b    c     d     e     f
0  1.0  2.0  3.0   NaN   NaN   NaN
1  4.0  5.0  6.0   NaN   NaN   NaN
0  NaN  NaN  NaN  10.0  20.0  30.0
1  NaN  NaN  NaN  40.0  50.0  60.0

In [146]:
pd.concat([df1,df10])# concatenating 2 dataset where we have no of column different

     a    b    c     d     e
0  1.0  2.0  3.0   NaN   NaN
1  4.0  5.0  6.0   NaN   NaN
0  NaN  NaN  NaN  10.0  20.0
1  NaN  NaN  NaN  40.0  50.0

In [148]:
d11=[[10,20],[40,50]]
df11=pd.DataFrame(d11,columns=['a','e'])
df11

    a   e
0  10  20
1  40  50

In [150]:
pd.concat([df1,df11])# concatenating 2 dataset where we have few column names are matching

    a    b    c     e
0   1  2.0  3.0   NaN
1   4  5.0  6.0   NaN
0  10  NaN  NaN  20.0
1  40  NaN  NaN  50.0

In [152]:
d15=[[1,2,3],[4,5,6]]
df15=pd.DataFrame(d15,columns=['a','b','c'])
d16=[[1,2,3],[7,5,6]]
df16=pd.DataFrame(d16,columns=['a','b','c'])
pd.concat([df15,df16]) # it will not remove duplicate row

   a  b  c
0  1  2  3
1  4  5  6
0  1  2  3
1  7  5  6

### 9.5.3 Merge

In [156]:
import numpy as np
d1 = {'movieid':[1,2,3,4,5],
     'title':['3 Idiots','2 States','Leo','RRR','Pushpa']}
movies = pd.DataFrame(d1)


d2 = {
    'memid':[1,2,3,4],
    'name':['Tom','Tim','Jon','Jim'],
    'movieid':[1,np.nan,3,5]
}
members=pd.DataFrame(d2)

In [158]:
print(movies)

   movieid     title
0        1  3 Idiots
1        2  2 States
2        3       Leo
3        4       RRR
4        5    Pushpa

In [160]:
print(members)

   memid name  movieid
0      1  Tom      1.0
1      2  Tim      NaN
2      3  Jon      3.0
3      4  Jim      5.0

In [162]:
pd.merge(movies,members) # it behaves like innner join. it it will find the same column name and join on the basis of that coulmn

   movieid     title  memid name
0        1  3 Idiots      1  Tom
1        3       Leo      3  Jon
2        5    Pushpa      4  Jim

In [164]:
pd.merge(movies,members,on='movieid') # explicitly also we can mention the column name to join

   movieid     title  memid name
0        1  3 Idiots      1  Tom
1        3       Leo      3  Jon
2        5    Pushpa      4  Jim

In [166]:
pd.merge(movies,members,on='movieid',how='right')

   movieid     title  memid name
0      1.0  3 Idiots      1  Tom
1      NaN       NaN      2  Tim
2      3.0       Leo      3  Jon
3      5.0    Pushpa      4  Jim

In [168]:
pd.merge(movies,members,left_on='movieid',right_on='movieid',how='right') # if we have different column name

   movieid     title  memid name
0      1.0  3 Idiots      1  Tom
1      NaN       NaN      2  Tim
2      3.0       Leo      3  Jon
3      5.0    Pushpa      4  Jim

In [170]:
pd.merge(movies,members,left_on='movieid',right_on='movieid',how='outer')

   movieid     title  memid name
0      1.0  3 Idiots    1.0  Tom
1      2.0  2 States    NaN  NaN
2      3.0       Leo    3.0  Jon
3      4.0       RRR    NaN  NaN
4      5.0    Pushpa    4.0  Jim
5      NaN       NaN    2.0  Tim

In [172]:
pd.merge(movies,members,left_on='movieid',right_on='movieid',how='outer') [['title','memid']]

      title  memid
0  3 Idiots    1.0
1  2 States    NaN
2       Leo    3.0
3       RRR    NaN
4    Pushpa    4.0
5       NaN    2.0

## 9.6 SORTING
Two ways of sorting
- 1) BY index
- 2) By column values

In [175]:
import pandas as pd
df=pd.read_csv('Universities.csv')

In [177]:
df

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [179]:
df.sort_index(ascending=False) # sorting by index

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
24          Yale  1375     95      19       11     43514        96
23    UWisconsin  1085     40      69       15     11857        71
22           UVA  1225     77      44       14     13349        92
21         UPenn  1285     80      36       11     27553        90
20     UMichigan  1180     65      68       16     15470        85
19      UChicago  1290     75      50       13     38380        87
18    UCBerkeley  1240     95      40       17     15140        78
17      TexasA&M  1075     49      67       25      8704        67
16      Stanford  1360     90      20       12     36450        93
15        Purdue  1005     28      90       19      9066        69
14     Princeton  1375     91      14        8     30220        95
13     PennState  1081     38      54       18     10185        80
12     NotreDame  1255     81      42       13     15122        94
11  Northwestern  1260     85      39       11     28052        89
10           MIT  1380     94      30       10     34870        91
9   JohnsHopkins  1305     75      44        7     58691        87
8        Harvard  1400     91      14       11     39525        97
7     Georgetown  1255     74      24       12     20126        92
6           Duke  1315     90      30       12     31585        95
5      Dartmouth  1340     89      23       10     32162        95
4        Cornell  1280     83      33       13     21864        90
3       Columbia  1310     76      24       12     31510        88
2            CMU  1260     62      59        9     25026        72
1        CalTech  1415    100      25        6     63575        81
0          Brown  1310     89      22       13     22704        94

In [181]:
df.sort_values(by='Expenses') # by default asc

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
17      TexasA&M  1075     49      67       25      8704        67
15        Purdue  1005     28      90       19      9066        69
13     PennState  1081     38      54       18     10185        80
23    UWisconsin  1085     40      69       15     11857        71
22           UVA  1225     77      44       14     13349        92
12     NotreDame  1255     81      42       13     15122        94
18    UCBerkeley  1240     95      40       17     15140        78
20     UMichigan  1180     65      68       16     15470        85
7     Georgetown  1255     74      24       12     20126        92
4        Cornell  1280     83      33       13     21864        90
0          Brown  1310     89      22       13     22704        94
2            CMU  1260     62      59        9     25026        72
21         UPenn  1285     80      36       11     27553        90
11  Northwestern  1260     85      39       11     28052        89
14     Princeton  1375     91      14        8     30220        95
3       Columbia  1310     76      24       12     31510        88
6           Duke  1315     90      30       12     31585        95
5      Dartmouth  1340     89      23       10     32162        95
10           MIT  1380     94      30       10     34870        91
16      Stanford  1360     90      20       12     36450        93
19      UChicago  1290     75      50       13     38380        87
8        Harvard  1400     91      14       11     39525        97
24          Yale  1375     95      19       11     43514        96
9   JohnsHopkins  1305     75      44        7     58691        87
1        CalTech  1415    100      25        6     63575        81

In [183]:
df.max() # gives the msx valu for each column

Univ         Yale
SAT          1415
Top10         100
Accept         90
SFRatio        25
Expenses    63575
GradRate       97
dtype: object

In [186]:
df.idxmax()

Univ        24
SAT          1
Top10        1
Accept      15
SFRatio     17
Expenses     1
GradRate     8
dtype: int64

In [188]:
df.min()

Univ        Brown
SAT          1005
Top10          28
Accept         14
SFRatio         6
Expenses     8704
GradRate       67
dtype: object

## 9.7 Grouping

In [191]:
import pandas as pd
df1=pd.read_csv(r'\Users\Pandhari\python_practice\Salaries.csv')
df1.head(5)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [193]:
df1['rank'].value_counts()# count of rows

rank
Prof         26
AsstProf     16
AssocProf     9
Name: count, dtype: int64

In [195]:
df1['rank'].unique()# unique values from the column

array(['Prof', 'AssocProf', 'AsstProf'], dtype=object)

In [197]:
df1['rank'].value_counts()

rank
Prof         26
AsstProf     16
AssocProf     9
Name: count, dtype: int64

In [199]:
#df1['rank','discipline'].value_counts()

#### 9.7.1 Variable unpacking
- Assigning values to the respective variable

In [202]:
grp=df1.groupby('rank')# it will store all records based on rank values like for each catory of rank it will store all corresponding records with rank category
grp

In [204]:
df1.head()

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [206]:
for x in grp:# if we want to extract the data we need to iterate it. if want to do grouping based on single column
    print(x)# not alligned properly # after applying grouping only we can find out aggregated output
    print('_'*100)

('AssocProf',          rank discipline  phd  service     sex  salary
2   AssocProf          A   20       17    Male   81285
17  AssocProf          B    9        7    Male  107008
19  AssocProf          B   12        8    Male  119800
23  AssocProf          A   13        8  Female   74830
26  AssocProf          B   11       11  Female  103613
34  AssocProf          B   12       10  Female  103994
37  AssocProf          A   26       24  Female   73300
44  AssocProf          B   12        9  Female   71065
47  AssocProf          B   19        6  Female  104542)
____________________________________________________________________________________________________
('AsstProf',         rank discipline  phd  service     sex  salary
4   AsstProf          B    1        0    Male   88000
6   AsstProf          B    8        3    Male   75044
7   AsstProf          B    4        0    Male   92000
10  AsstProf          B    4        4    Male   92000
12  AsstProf          A    4        2    Male   73000
13  AsstProf          A    2        0    Male   85000
15  AsstProf          B    7        2    Male   91300
21  AsstProf          B    4        3    Male   91000
25  AsstProf          B   11        3  Female   74692
28  AsstProf          B   10        5  Female   97032
31  AsstProf          A    5        3  Female   73500
32  AsstProf          A    3        1  Female   72500
35  AsstProf          B    3        3  Female   92000
39  AsstProf          A    7        6  Female   63100
41  AsstProf          A    4        2  Female   77500
43  AsstProf          A    8        3  Female   78500)
____________________________________________________________________________________________________
('Prof',     rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
8   Prof          A   19        7    Male  107300
9   Prof          A   29       27    Male  150500
11  Prof          A   33       30    Male  103106
14  Prof          A   30       23    Male   91100
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
27  Prof          B   17       17  Female  111512
29  Prof          B   20       14  Female  127512
30  Prof          A   12        0  Female  105000
33  Prof          B   36       26  Female  144651
36  Prof          A   29       27  Female   91000
38  Prof          A   36       19  Female  117555
40  Prof          A   17       11  Female   90450
42  Prof          A   28        7  Female  116450
45  Prof          B   24       15  Female  161101
46  Prof          B   18       10  Female  105450
48  Prof          B   17       17  Female  124312
49  Prof          A   28       14  Female  109954
50  Prof          A   23       15  Female  109646)
____________________________________________________________________________________________________

In [214]:
for x,y in grp:
    print(x)
    print('_'*100)

AssocProf
____________________________________________________________________________________________________
AsstProf
____________________________________________________________________________________________________
Prof
____________________________________________________________________________________________________

In [216]:
for x,y in grp:
    print(y)
    print('_'*100) # If we see the difference between above 2 code. X - holds only group name, y- holds real records. It useful when we want to show aligned data

         rank discipline  phd  service     sex  salary
2   AssocProf          A   20       17    Male   81285
17  AssocProf          B    9        7    Male  107008
19  AssocProf          B   12        8    Male  119800
23  AssocProf          A   13        8  Female   74830
26  AssocProf          B   11       11  Female  103613
34  AssocProf          B   12       10  Female  103994
37  AssocProf          A   26       24  Female   73300
44  AssocProf          B   12        9  Female   71065
47  AssocProf          B   19        6  Female  104542
____________________________________________________________________________________________________
        rank discipline  phd  service     sex  salary
4   AsstProf          B    1        0    Male   88000
6   AsstProf          B    8        3    Male   75044
7   AsstProf          B    4        0    Male   92000
10  AsstProf          B    4        4    Male   92000
12  AsstProf          A    4        2    Male   73000
13  AsstProf          A    2        0    Male   85000
15  AsstProf          B    7        2    Male   91300
21  AsstProf          B    4        3    Male   91000
25  AsstProf          B   11        3  Female   74692
28  AsstProf          B   10        5  Female   97032
31  AsstProf          A    5        3  Female   73500
32  AsstProf          A    3        1  Female   72500
35  AsstProf          B    3        3  Female   92000
39  AsstProf          A    7        6  Female   63100
41  AsstProf          A    4        2  Female   77500
43  AsstProf          A    8        3  Female   78500
____________________________________________________________________________________________________
    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
8   Prof          A   19        7    Male  107300
9   Prof          A   29       27    Male  150500
11  Prof          A   33       30    Male  103106
14  Prof          A   30       23    Male   91100
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
27  Prof          B   17       17  Female  111512
29  Prof          B   20       14  Female  127512
30  Prof          A   12        0  Female  105000
33  Prof          B   36       26  Female  144651
36  Prof          A   29       27  Female   91000
38  Prof          A   36       19  Female  117555
40  Prof          A   17       11  Female   90450
42  Prof          A   28        7  Female  116450
45  Prof          B   24       15  Female  161101
46  Prof          B   18       10  Female  105450
48  Prof          B   17       17  Female  124312
49  Prof          A   28       14  Female  109954
50  Prof          A   23       15  Female  109646
____________________________________________________________________________________________________

In [81]:
grp.agg('mean',numeric_only='True')

                 phd    service         salary
rank
AssocProf  14.888889  11.111111   93270.777778
AsstProf    5.312500   2.500000   82260.500000
Prof       26.307692  20.038462  125561.615385

In [83]:
grp.agg('max',numeric_only=True)

           phd  service  salary
rank
AssocProf   26       24  119800
AsstProf    11        6   97032
Prof        56       49  186960

In [86]:
# grouping based on multiple column
grp2=df1.groupby(['rank','sex'])
for x,y in grp2:
    print(x,y)
    print('_'*50)

('AssocProf', 'Female')          rank discipline  phd  service     sex  salary
23  AssocProf          A   13        8  Female   74830
26  AssocProf          B   11       11  Female  103613
34  AssocProf          B   12       10  Female  103994
37  AssocProf          A   26       24  Female   73300
44  AssocProf          B   12        9  Female   71065
47  AssocProf          B   19        6  Female  104542
__________________________________________________
('AssocProf', 'Male')          rank discipline  phd  service   sex  salary
2   AssocProf          A   20       17  Male   81285
17  AssocProf          B    9        7  Male  107008
19  AssocProf          B   12        8  Male  119800
__________________________________________________
('AsstProf', 'Female')         rank discipline  phd  service     sex  salary
25  AsstProf          B   11        3  Female   74692
28  AsstProf          B   10        5  Female   97032
31  AsstProf          A    5        3  Female   73500
32  AsstProf          A    3        1  Female   72500
35  AsstProf          B    3        3  Female   92000
39  AsstProf          A    7        6  Female   63100
41  AsstProf          A    4        2  Female   77500
43  AsstProf          A    8        3  Female   78500
__________________________________________________
('AsstProf', 'Male')         rank discipline  phd  service   sex  salary
4   AsstProf          B    1        0  Male   88000
6   AsstProf          B    8        3  Male   75044
7   AsstProf          B    4        0  Male   92000
10  AsstProf          B    4        4  Male   92000
12  AsstProf          A    4        2  Male   73000
13  AsstProf          A    2        0  Male   85000
15  AsstProf          B    7        2  Male   91300
21  AsstProf          B    4        3  Male   91000
__________________________________________________
('Prof', 'Female')     rank discipline  phd  service     sex  salary
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
27  Prof          B   17       17  Female  111512
29  Prof          B   20       14  Female  127512
30  Prof          A   12        0  Female  105000
33  Prof          B   36       26  Female  144651
36  Prof          A   29       27  Female   91000
38  Prof          A   36       19  Female  117555
40  Prof          A   17       11  Female   90450
42  Prof          A   28        7  Female  116450
45  Prof          B   24       15  Female  161101
46  Prof          B   18       10  Female  105450
48  Prof          B   17       17  Female  124312
49  Prof          A   28       14  Female  109954
50  Prof          A   23       15  Female  109646
__________________________________________________
('Prof', 'Male')     rank discipline  phd  service   sex  salary
0   Prof          B   56       49  Male  186960
1   Prof          A   20       20  Male  122400
3   Prof          B   23       23  Male  134778
5   Prof          B   17        3  Male  150480
8   Prof          A   19        7  Male  107300
9   Prof          A   29       27  Male  150500
11  Prof          A   33       30  Male  103106
14  Prof          A   30       23  Male   91100
16  Prof          B   21       20  Male  123683
18  Prof          B   22       21  Male  155750
20  Prof          B   45       45  Male  146856
__________________________________________________

In [87]:
grp2.agg('mean',numeric_only=True)

                        phd    service         salary
rank      sex
AssocProf Female  15.500000  11.333333   88557.333333
          Male    13.666667  10.666667  102697.666667
AsstProf  Female   6.375000   3.250000   78603.000000
          Male     4.250000   1.750000   85918.000000
Prof      Female  24.600000  16.866667  119445.933333
          Male    28.636364  24.363636  133901.181818

In [90]:
# grp.agg(['mean','max','min'],numeric_only=True)# if we want to group based on multiple columns, we can use this

In [98]:
grp3=df1[['service','salary','rank','sex']].groupby(['rank','sex']) # if we want to group based on multiple columns, extract all the coumns of no  data type along with aggregted column
for i in grp3:
    print(i)
    print('_'*50)
# grp3 -- u can check whether it has creaated or not

(('AssocProf', 'Female'),     service  salary       rank     sex
23        8   74830  AssocProf  Female
26       11  103613  AssocProf  Female
34       10  103994  AssocProf  Female
37       24   73300  AssocProf  Female
44        9   71065  AssocProf  Female
47        6  104542  AssocProf  Female)
__________________________________________________
(('AssocProf', 'Male'),     service  salary       rank   sex
2        17   81285  AssocProf  Male
17        7  107008  AssocProf  Male
19        8  119800  AssocProf  Male)
__________________________________________________
(('AsstProf', 'Female'),     service  salary      rank     sex
25        3   74692  AsstProf  Female
28        5   97032  AsstProf  Female
31        3   73500  AsstProf  Female
32        1   72500  AsstProf  Female
35        3   92000  AsstProf  Female
39        6   63100  AsstProf  Female
41        2   77500  AsstProf  Female
43        3   78500  AsstProf  Female)
__________________________________________________
(('AsstProf', 'Male'),     service  salary      rank   sex
4         0   88000  AsstProf  Male
6         3   75044  AsstProf  Male
7         0   92000  AsstProf  Male
10        4   92000  AsstProf  Male
12        2   73000  AsstProf  Male
13        0   85000  AsstProf  Male
15        2   91300  AsstProf  Male
21        3   91000  AsstProf  Male)
__________________________________________________
(('Prof', 'Female'),     service  salary  rank     sex
22       36  137000  Prof  Female
24       25  140096  Prof  Female
27       17  111512  Prof  Female
29       14  127512  Prof  Female
30        0  105000  Prof  Female
33       26  144651  Prof  Female
36       27   91000  Prof  Female
38       19  117555  Prof  Female
40       11   90450  Prof  Female
42        7  116450  Prof  Female
45       15  161101  Prof  Female
46       10  105450  Prof  Female
48       17  124312  Prof  Female
49       14  109954  Prof  Female
50       15  109646  Prof  Female)
__________________________________________________
(('Prof', 'Male'),     service  salary  rank   sex
0        49  186960  Prof  Male
1        20  122400  Prof  Male
3        23  134778  Prof  Male
5         3  150480  Prof  Male
8         7  107300  Prof  Male
9        27  150500  Prof  Male
11       30  103106  Prof  Male
14       23   91100  Prof  Male
16       20  123683  Prof  Male
18       21  155750  Prof  Male
20       45  146856  Prof  Male)
__________________________________________________

In [100]:

grp3.agg(['min','max','mean'])
# E1 - rank and sex wise wise min,max,mean of phd,service and salary

                 service                salary
                     min max       mean    min     max           mean
rank      sex
AssocProf Female       6  24  11.333333  71065  104542   88557.333333
          Male         7  17  10.666667  81285  119800  102697.666667
AsstProf  Female       1   6   3.250000  63100   97032   78603.000000
          Male         0   4   1.750000  73000   92000   85918.000000
Prof      Female       0  36  16.866667  90450  161101  119445.933333
          Male         3  49  24.363636  91100  186960  133901.181818

In [45]:
grp4=df1[['service','salary','rank','sex']].groupby(['rank','sex']) # if we want to group based on multiple columns(required for aggragtion), extract all the coumns along with aggregted column
# grp3 -- u can check whether it has creaated or not
grp4.agg(['min','max','mean'])

                 service                salary
                     min max       mean    min     max           mean
rank      sex
AssocProf Female       6  24  11.333333  71065  104542   88557.333333
          Male         7  17  10.666667  81285  119800  102697.666667
AsstProf  Female       1   6   3.250000  63100   97032   78603.000000
          Male         0   4   1.750000  73000   92000   85918.000000
Prof      Female       0  36  16.866667  90450  161101  119445.933333
          Male         3  49  24.363636  91100  186960  133901.181818

# 10 Series
- A perticular column outof datframe is series. So data frame is series of series

In [202]:
type(df1['rank'])

pandas.core.series.Series

In [2]:
#type(df1['rank','phd'])

In [10]:
import pandas as pd

In [62]:
data=pd.DataFrame([
        [100,'Tom','MGR',4500],
        [200,'Mary','Pgmr',6000],
        [300,'JOn','HR',5400],
        [400,'Larry','pgmr',7800],
        [500,'Peter','Clerk',3500],
        [600,'Kate','HR',400]
     ])

In [64]:
data

     0      1      2     3
0  100    Tom    MGR  4500
1  200   Mary   Pgmr  6000
2  300    JOn     HR  5400
3  400  Larry   pgmr  7800
4  500  Peter  Clerk  3500
5  600   Kate     HR   400

In [66]:
data.columns=['jobid','name','role','sal']
data

   jobid   name   role   sal
0    100    Tom    MGR  4500
1    200   Mary   Pgmr  6000
2    300    JOn     HR  5400
3    400  Larry   pgmr  7800
4    500  Peter  Clerk  3500
5    600   Kate     HR   400

In [22]:
data['jobid']

0    100
1    200
2    300
3    400
4    500
5    600
Name: jobid, dtype: int64

In [24]:
type(data['jobid'])

pandas.core.series.Series

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   jobid   6 non-null      int64
 1   name    6 non-null      object
 2   role    6 non-null      object
 3   sal     6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [60]:
#des.data

NameError: name 'des' is not defined

In [36]:
data[['jobid','name']] # to display multiple coulns awe need to mentionlist oof columns into list

   jobid   name
0    100    Tom
1    200   Mary
2    300    JOn
3    400  Larry
4    500  Peter
5    600   Kate

In [40]:
type(data[['jobid','name']]) # it is dataaframe not a series

pandas.core.frame.DataFrame

In [52]:
def rate_inc(sal):
    if sal > 5000:
        res='good'
    else:
        res='ok'
    return res

In [46]:
rate_inc(2000)

'ok'

In [70]:
data['sal'].apply(rate_inc)

0      ok
1    good
2    good
3    good
4      ok
5      ok
Name: sal, dtype: object

In [74]:
data['status']=data['sal'].apply(rate_inc) # this is time concsuming and may be, intead we can use lmda function
data

   jobid   name   role   sal status
0    100    Tom    MGR  4500     ok
1    200   Mary   Pgmr  6000   good
2    300    JOn     HR  5400   good
3    400  Larry   pgmr  7800   good
4    500  Peter  Clerk  3500     ok
5    600   Kate     HR   400     ok

In [82]:
data['status1']= data['sal'].apply(lambda x: 'good' if x>5000 else 'ok')
data

   jobid   name   role   sal status status1
0    100    Tom    MGR  4500     ok      ok
1    200   Mary   Pgmr  6000   good    good
2    300    JOn     HR  5400   good    good
3    400  Larry   pgmr  7800   good    good
4    500  Peter  Clerk  3500     ok      ok
5    600   Kate     HR   400     ok      ok