# 8 DataFrames/Pandas / EDA
- Pandas are basicaly built to deal with 2 dimential data.
-

## 8.1 We can create the dataframe is 3 ways
- By using multiple list
- By using dictionary
- reading external systetm

In [1]:
import pandas as pd

In [3]:
# Create data frame by using list
import pandas as pd
data=[
        [100,'Tom','MGR','4500'],
        [200,'Mary','Pgmr','6000'],
        [300,'JOn','HR',5400]
     ]

In [5]:
data

[[100, 'Tom', 'MGR', '4500'],
 [200, 'Mary', 'Pgmr', '6000'],
 [300, 'JOn', 'HR', 5400]]

In [17]:
print(data[0])

[100, 'Tom', 'MGR', '4500']

In [19]:
print(data[1])

[200, 'Mary', 'Pgmr', '6000']

In [21]:
type(data) # this is a list, still it is not a dataFrame. Tp careate a data frame we need to use DataFrame method from pandas

list

In [72]:
df=pd.DataFrame(data)
df

     0     1     2     3
0  100   Tom   MGR  4500
1  200  Mary  Pgmr  6000
2  300   JOn    HR  5400

In [74]:
type(df)

pandas.core.frame.DataFrame

In [76]:
df1=pd.DataFrame([
        [100,'Tom','MGR','4500'],
        [200,'Mary','Pgmr','6000'],
        [300,'JOn','HR',5400]
     ]) #Or also you can pass vaues directly to create dataframe

In [78]:
df1

     0     1     2     3
0  100   Tom   MGR  4500
1  200  Mary  Pgmr  6000
2  300   JOn    HR  5400

In [80]:
type(df1)

pandas.core.frame.DataFrame

In [82]:
# assign the name to careated dataframe

In [84]:
df2=pd.DataFrame(data,columns=['Eid','Ename','Job','Salary'])
df2

   Eid Ename   Job Salary
0  100   Tom   MGR   4500
1  200  Mary  Pgmr   6000
2  300   JOn    HR   5400

In [89]:
df3=pd.DataFrame(data,columns=['Eid','Ename','Job','Salary'],index=['r1','r2','r3']) # we can assign the index manually as well
df3

    Eid Ename   Job Salary
r1  100   Tom   MGR   4500
r2  200  Mary  Pgmr   6000
r3  300   JOn    HR   5400

In [93]:
import pandas as pd
df=pd.read_csv('Universities.csv')
df.head(5)

       Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0     Brown  1310     89      22       13     22704        94
1   CalTech  1415    100      25        6     63575        81
2       CMU  1260     62      59        9     25026        72
3  Columbia  1310     76      24       12     31510        88
4   Cornell  1280     83      33       13     21864        90

## 8.3 Read data from external sources

In [96]:
df1=pd.read_csv(r'\Users\Pandhari\python_practice\Salaries.csv')
df1.head(5)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

### 8.3.1 Examine data

In [99]:
type(df)

pandas.core.frame.DataFrame

In [101]:
df.head() # by default first 5 records

       Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0     Brown  1310     89      22       13     22704        94
1   CalTech  1415    100      25        6     63575        81
2       CMU  1260     62      59        9     25026        72
3  Columbia  1310     76      24       12     31510        88
4   Cornell  1280     83      33       13     21864        90

In [103]:
df.head(10)

           Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0         Brown  1310     89      22       13     22704        94
1       CalTech  1415    100      25        6     63575        81
2           CMU  1260     62      59        9     25026        72
3      Columbia  1310     76      24       12     31510        88
4       Cornell  1280     83      33       13     21864        90
5     Dartmouth  1340     89      23       10     32162        95
6          Duke  1315     90      30       12     31585        95
7    Georgetown  1255     74      24       12     20126        92
8       Harvard  1400     91      14       11     39525        97
9  JohnsHopkins  1305     75      44        7     58691        87

In [105]:
df.tail() # by default last 5 records

          Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
20   UMichigan  1180     65      68       16     15470        85
21       UPenn  1285     80      36       11     27553        90
22         UVA  1225     77      44       14     13349        92
23  UWisconsin  1085     40      69       15     11857        71
24        Yale  1375     95      19       11     43514        96

In [107]:
df.shape # rows, columns

(25, 7)

In [109]:
df.columns

Index(['Univ', 'SAT', 'Top10', 'Accept', 'SFRatio', 'Expenses', 'GradRate'], dtype='object')

In [111]:
df.index

RangeIndex(start=0, stop=25, step=1)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Univ      25 non-null     object
 1   SAT       25 non-null     int64
 2   Top10     25 non-null     int64
 3   Accept    25 non-null     int64
 4   SFRatio   25 non-null     int64
 5   Expenses  25 non-null     int64
 6   GradRate  25 non-null     int64
dtypes: int64(6), object(1)
memory usage: 1.5+ KB

In [115]:
df.describe()# it works only for numeric data

               SAT       Top10     Accept   SFRatio      Expenses   GradRate
count    25.000000   25.000000  25.000000  25.00000     25.000000  25.000000
mean   1266.440000   76.480000  39.200000  12.72000  27388.000000  86.720000
std     108.359771   19.433905  19.727308   4.06735  14424.883165   9.057778
min    1005.000000   28.000000  14.000000   6.00000   8704.000000  67.000000
25%    1240.000000   74.000000  24.000000  11.00000  15140.000000  81.000000
50%    1285.000000   81.000000  36.000000  12.00000  27553.000000  90.000000
75%    1340.000000   90.000000  50.000000  14.00000  34870.000000  94.000000
max    1415.000000  100.000000  90.000000  25.00000  63575.000000  97.000000

## 8.3.2 accessing data from dataframe

In [119]:
#dataframe[rows,columns]
#dataframe[startpos:endpos,startpos:endpos]
# .loc will be used to access the entire record of that perticular index
# .iloc will be used to access the columns with column and row index

In [123]:
df.loc[20]

Univ        UMichigan
SAT              1180
Top10              65
Accept             68
SFRatio            16
Expenses        15470
GradRate           85
Name: 20, dtype: object

In [127]:
df.loc[20,'Expenses'] # 20th index record and Expenses column value

15470

In [129]:
df['Univ'] # if we wanr to extract perticular column

0            Brown
1          CalTech
2              CMU
3         Columbia
4          Cornell
5        Dartmouth
6             Duke
7       Georgetown
8          Harvard
9     JohnsHopkins
10             MIT
11    Northwestern
12       NotreDame
13       PennState
14       Princeton
15          Purdue
16        Stanford
17        TexasA&M
18      UCBerkeley
19        UChicago
20       UMichigan
21           UPenn
22             UVA
23      UWisconsin
24            Yale
Name: Univ, dtype: object

In [131]:
df.loc[:,'Univ'] ## all rows but Univ column

0            Brown
1          CalTech
2              CMU
3         Columbia
4          Cornell
5        Dartmouth
6             Duke
7       Georgetown
8          Harvard
9     JohnsHopkins
10             MIT
11    Northwestern
12       NotreDame
13       PennState
14       Princeton
15          Purdue
16        Stanford
17        TexasA&M
18      UCBerkeley
19        UChicago
20       UMichigan
21           UPenn
22             UVA
23      UWisconsin
24            Yale
Name: Univ, dtype: object

In [133]:
df.loc[:2,'Univ']

0      Brown
1    CalTech
2        CMU
Name: Univ, dtype: object

In [135]:
df.iloc[:2,1:4] # frist 2 rows and 3 columns frm indexing 1 to 3

    SAT  Top10  Accept
0  1310     89      22
1  1415    100      25

In [148]:
df.loc[[0,3],['SAT'	,'Top10','Accept']]

    SAT  Top10  Accept
0  1310     89      22
3  1310     76      24

### 8.3.1 Cleaning data

In [49]:
#dir(pd.DataFrame)
dir