# 13 Descriptive statistics
- 17-mar-25
- 13.1 Measures of frequency
- -- 13.1.1 counts
- -- 13.1.2 frequency
- -- 13.1.3 percentage
- 13.2 Measures of central tendency
- -- 13.2.1 mean
- -- 13.2.2 median
- -- 13.2.3 mode
- 13.3 Merasures dispersion
- -- 13.3.1 Range
- -- 13.3.2 variance\
- -- 13.3.3 standard deviation
- 13.4 measures of position
- -- 13.4.1 perncentile
- -- 13.4.2 decile
- -- 13.4.3 quartile
- 13.5 shape
- -- 13.5.1 skewness
- -- 13.5.2 kurtosis

## 13.1 Measures of frequency

In [3]:
import pandas as pd

data = ['Apple', 'Banana', 'Apple', 'Orange', 'Banana', 'Apple', 'Mango', 'Banana', 'Apple', 'Orange']
df = pd.DataFrame(data, columns=['Fruit'])

# Frequency
freq = df['Fruit'].value_counts()

# Relative Frequency
rel_freq = df['Fruit'].value_counts(normalize=True) * 100

# Cumulative Frequency
cum_freq = df['Fruit'].value_counts().cumsum()

# Combine
summary = pd.DataFrame({
    'Frequency': freq,
    'Relative Frequency (%)': rel_freq.round(2),
    'Cumulative Frequency': cum_freq
})

print(summary)

        Frequency  Relative Frequency (%)  Cumulative Frequency
Fruit
Apple           4                    40.0                     4
Banana          3                    30.0                     7
Orange          2                    20.0                     9
Mango           1                    10.0                    10

## 13.2 Measures of central tendency

In [8]:
import pandas as pd
df1=pd.read_csv(r'\Users\Pandhari\python_practice\Salaries.csv')
df1.head(5)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [3]:
df1['salary'].mean()

106278.56862745098

In [10]:
df1['salary'].median()

103994.0

In [12]:
df1['rank'].mode()

0    Prof
Name: rank, dtype: object

In [16]:
df1['rank'].value_counts()

rank
Prof         26
AsstProf     16
AssocProf     9
Name: count, dtype: int64

In [18]:
df1['discipline'].mode()

0    B
Name: discipline, dtype: object

## 13.3 Measures of dispersion

In [50]:
marks=[87,93,69,56,43,88,23,50,44,75,75,93,56,75,43,37,65,77,80,43]
marks_df1=pd.DataFrame(marks,columns=['marks'])
marks_df1.head()

   marks
0     87
1     93
2     69
3     56
4     43

In [52]:
marks_df1.mean()

marks    63.6
dtype: float64

In [54]:
marks_df1.std()

marks    20.589727
dtype: float64

In [56]:
marks_df1.var()

marks    423.936842
dtype: float64

In [62]:
range=marks_df.max()-marks_df.min()
range

marks         70.0
percentile    92.5
dtype: float64

## 13.4 Measures of position

In [9]:
import pandas as pd
df1=pd.read_csv(r'\Users\Pandhari\python_practice\Salaries.csv')
df1.head(5)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [35]:
marks=[87,69,93,56,43,88,23,50,44,75,75,93,56,75,43,37,65,77,80,43]

In [37]:
import numpy as np

In [39]:
# convert the list into dataframe for better understnding

In [41]:
marks_df=pd.DataFrame(marks,columns=['marks'])
marks_df.head()

   marks
0     87
1     69
2     93
3     56
4     43

In [43]:
type(marks_df)

pandas.core.frame.DataFrame

In [45]:
np.percentile(marks,25) # means 25 percent of data lies below 43.75.

43.75

In [47]:
np.percentile(marks,100) # means 100 percent of data lies below 93.

93.0

In [49]:
# display percentile of each number.

In [51]:
# find out the percentile of each data point
marks_df['marks'].rank(pct=True)*100 #but htis will give us only percentile but we need display data points also along with

0     85.0
1     55.0
2     97.5
3     42.5
4     20.0
5     90.0
6      5.0
7     35.0
8     30.0
9     65.0
10    65.0
11    97.5
12    42.5
13    65.0
14    20.0
15    10.0
16    50.0
17    75.0
18    80.0
19    20.0
Name: marks, dtype: float64

In [53]:
marks_df['percentile']=marks_df['marks'].rank(pct=True)*100 # this will add percentile column to dataframe

In [55]:
marks_df

    marks  percentile
0      87        85.0
1      69        55.0
2      93        97.5
3      56        42.5
4      43        20.0
5      88        90.0
6      23         5.0
7      50        35.0
8      44        30.0
9      75        65.0
10     75        65.0
11     93        97.5
12     56        42.5
13     75        65.0
14     43        20.0
15     37        10.0
16     65        50.0
17     77        75.0
18     80        80.0
19     43        20.0

In [57]:
np.percentile(marks_df,100)

97.5

In [59]:
np.percentile(marks_df,50)

60.5

In [61]:
marks_df.sort_values(by='marks', ascending=False)

    marks  percentile
2      93        97.5
11     93        97.5
5      88        90.0
0      87        85.0
18     80        80.0
17     77        75.0
9      75        65.0
13     75        65.0
10     75        65.0
1      69        55.0
16     65        50.0
12     56        42.5
3      56        42.5
7      50        35.0
8      44        30.0
14     43        20.0
4      43        20.0
19     43        20.0
15     37        10.0
6      23         5.0

# 13.5 Measures of shape(skewness and kurtosis)