# 33.2) EDA – part 2

In [1]:
import pandas as pd
import sklearn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [2]:
iris=pd.read_csv('iris.csv')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## 33.2.1 Label encoding

In [6]:
iris_label=iris.copy()
iris_label.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
print(iris_label['species'])

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [10]:
le_enc=LabelEncoder()
le_enc.fit_transform(iris_label['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
iris_label['species']=le_enc.fit_transform(iris_label['species']) # lets replace species column values with encoder output

In [16]:
iris_label.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [18]:
iris_label.tail()

     sepal_length  sepal_width  petal_length  petal_width  species
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

- AFtfer this we can use this dataset to feed it to x_Train and y_train

## 33.2.1 OHE encoding - One hot encoding

In [23]:
iris_ohe=iris.copy()
iris_ohe.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
ohe_enc=OneHotEncoder()
#ohe_enc.fit_transform([iris_label['species']]) # it is not possible to see output directly as it is parse matridx, so convert it into array and then arrat
pd.DataFrame(ohe_enc.fit_transform(iris_ohe[['species']]).toarray())

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [27]:
iris_final_ohe=iris_ohe.join(pd.DataFrame(ohe_enc.fit_transform(iris_ohe[['species']]).toarray()))
iris_final_ohe

,sepal_length,sepal_width,petal_length,petal_width,species,0,1,2
0,5.1,3.5,1.4,0.2,setosa,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,setosa,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,setosa,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,setosa,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,setosa,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,virginica,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,virginica,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,virginica,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,virginica,0.0,0.0,1.0

In [29]:
iris_final_ohe.drop('species',axis=1,inplace=True)

In [31]:
iris_final_ohe.head()

   sepal_length  sepal_width  petal_length  petal_width    0    1    2
0           5.1          3.5           1.4          0.2  1.0  0.0  0.0
1           4.9          3.0           1.4          0.2  1.0  0.0  0.0
2           4.7          3.2           1.3          0.2  1.0  0.0  0.0
3           4.6          3.1           1.5          0.2  1.0  0.0  0.0
4           5.0          3.6           1.4          0.2  1.0  0.0  0.0

In [33]:
iris_final_ohe.rename(columns={0:'species_setos',1:'species_versicolor',2:'species_virgina'},inplace=True)

In [35]:
iris_final_ohe.head()

,sepal_length,sepal_width,petal_length,petal_width,species_setos,species_versicolor,species_virgina
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0

### OHE by using get dummies

In [38]:
iris_dum=iris.copy()

In [40]:
pd.get_dummies(iris_dum)

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

# 33.3 PPE score

In [17]:
#!pip install ppscore

In [107]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\pandhari\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\pandhari\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pandhari\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pandhari\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pandhari\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\pandhari\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [109]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\pandhari\anaconda3\lib\site-packages (1.26.4)

In [ ]:
import ppscore as pps

In [96]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
pps.score(iris,'sepal_width','petal_width') # classifiocation model

In [ ]:
pps.score(iris,'petal_length','species') # classifiocation model

In [ ]:
pps.matrix(iris)

# 33.3 Isolation forest

In [20]:
from sklearn.ensemble import IsolationForest

In [24]:
iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [34]:
iris_features=iris.iloc[:,0:4]

In [36]:
iso=IsolationForest(contamination=0.02)
iso.fit(iris_features)

IsolationForest(contamination=0.02)

In [38]:
iso.predict(iris_features)

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [40]:
iris_features['anamoly']=iso.predict(iris_features)

In [42]:
iris_features.head()

   sepal_length  sepal_width  petal_length  petal_width  anamoly
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [48]:
iris_features[iris_features['anamoly']==-1]

     sepal_length  sepal_width  petal_length  petal_width  anamoly
117           7.7          3.8           6.7          2.2       -1
118           7.7          2.6           6.9          2.3       -1
131           7.9          3.8           6.4          2.0       -1